DELETE http://localhost:3001/api/blogs/604560f7253cee1c4c9c3eaa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdodW9uZyIsImlkIjoiNjA2MDdhMjU1ZWQ4YjM0ZDNhYmMxOGFhIiwiaWF0IjoxNjE2OTQ0NDQ1LCJleHAiOjE2MTY5NDgwNDV9.HiCiAy_m4vek9HTs53BVnAkofz5V-pDUE1ymldi48bQ